### ISSUE TITLE
Build failure on GHC 8.4.3

### ISSUE THREAD

**Issue by jkachmar** [mniip/finite-typelits#12]
`finite-typelits-0.1.4.1` fails to build on GHC 8.4.3 with the following error:
```
Building library for finite-typelits-0.1.4.1..
[1 of 2] Compiling Data.Finite.Internal ( src/Data/Finite/Internal.hs, dist/build/Data/Finite/Internal.o )

src/Data/Finite/Internal.hs:96:10: error:
    • No instance for (GHC.Generics.Generic (Finite n))
        arising from a use of ‘Control.DeepSeq.$dmrnf’
    • In the expression: Control.DeepSeq.$dmrnf @(Finite n)
      In an equation for ‘rnf’: rnf = Control.DeepSeq.$dmrnf @(Finite n)
      In the instance declaration for ‘NFData (Finite n)’
   |
96 | instance NFData (Finite n)
   |          ^^^^^^^^^^^^^^^^^
```

**Comment by mniip** [comment]
Moral of the story: check the working directory and index for uncommitted stuff when doing `cabal sdist`.
