### ISSUE TITLE
finite-typelits doesn't build with ghc 8.6

### ISSUE THREAD

**Issue by expipiplus1** [mniip/finite-typelits#11]
```
[1 of 2] Compiling Data.Finite.Internal ( src/Data/Finite/Internal.hs, dist/build/Data/Finite/Internal.o )
[2 of 2] Compiling Data.Finite      ( src/Data/Finite.hs, dist/build/Data/Finite.o )

src/Data/Finite.hs:150:45: error:
    • Expected kind ‘* -> Nat -> Nat’, but ‘n’ has kind ‘Nat’
    • In the first argument of ‘Finite’, namely ‘(n * m)’
      In the type signature:
        multiply :: Finite n -> Finite m -> Finite (n * m)
    |
150 | multiply :: Finite n -> Finite m -> Finite (n * m)
    |                                             ^^^^^

src/Data/Finite.hs:162:65: error:
    • Expected kind ‘* -> Nat -> Nat’, but ‘n’ has kind ‘Nat’
    • In the first argument of ‘Finite’, namely ‘(n * m)’
      In the type signature:
        combineProduct :: KnownNat n =>
                          (Finite n, Finite m) -> Finite (n * m)
    |
162 | combineProduct :: KnownNat n => (Finite n, Finite m) -> Finite (n * m)
    |                                                                 ^^^^^

src/Data/Finite.hs:174:42: error:
    • Expected kind ‘* -> Nat -> Nat’, but ‘n’ has kind ‘Nat’
    • In the first argument of ‘Finite’, namely ‘(n * m)’
      In the type signature:
        separateProduct :: KnownNat n =>
                           Finite (n * m) -> (Finite n, Finite m)
    |
174 | separateProduct :: KnownNat n => Finite (n * m) -> (Finite n, Finite m)
    |                                          ^^^^^
```

**Comment by mniip** [comment]
Is this with or without TypeOperators => NoStarIsType?

**Comment by mniip** [comment]
I was able to build it on GHC HEAD. I'm assuming this is an issue with the 8.6.1-alpha1. Checking.

**Comment by expipiplus1** [comment]
Thanks!
